## Use an official OpenJDK runtime as a parent image
#FROM openjdk:17
#
## Set the working directory in the container
#WORKDIR /app
#
## Copy the local jar file to the container
#COPY target/mychaosApp-0.0.1-SNAPSHOT.jar mychaosApp-0.0.1-SNAPSHOT.jar
#
## Run the jar file
#ENTRYPOINT ["java", "-jar", "mychaosApp-0.0.1-SNAPSHOT.jar"]
##
##FROM java:8
##WORKDIR /
##ADD HelloWorld.jar HelloWorld.jar
##EXPOSE 8080
##CMD java - jar HelloWorld.jar